name: azure deploy

on:
  [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: WillAbides/setup-go-faster@v1
        with:
          go-version: 1.15.x
      - run: make azbin/handler
      - uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: willabides
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
