name: azure deploy

on:
  [workflow_dispatch]

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make azbin/handler
      - uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: willabides
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
